# Generated by Django 4.2.2 on 2023-12-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jersey_store', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='shipping',
        ),
    ]
