# Generated by Django 4.2.2 on 2023-12-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jersey_store', '0003_rename_digital_product_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping',
        ),
    ]
