# Generated by Django 4.2.2 on 2023-12-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jersey_store', '0004_remove_product_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
