# Generated by Django 4.2.2 on 2023-12-22 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jersey_store', '0005_frontendimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrontendImages',
        ),
    ]
