# Generated by Django 5.0 on 2023-12-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jersey_store', '0006_delete_frontendimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.CharField(blank=True, choices=[('M', 'Mens'), ('W', 'Womens'), ('K', 'Kids')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('Xl', 'Xtra Large'), ('M', 'Medium'), ('XXL', 'Xtra Xtra Large')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.CharField(blank=True, choices=[('J', 'Jersey'), ('B', 'Boots'), ('A', 'Accessories')], max_length=10, null=True),
        ),
    ]
