# Generated by Django 5.0 on 2023-12-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jersey_store', '0009_remove_customer_category_remove_customer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Mens', 'Mens'), ('Womens', 'Womens'), ('Kids', 'Kids')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('Xl', 'Xtra Large'), ('M', 'Medium'), ('XXL', 'Xtra Xtra Large')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('Jersey', 'Jersey'), ('Boots', 'Boots'), ('Accessories', 'Accessories')], max_length=50, null=True),
        ),
    ]
