# Generated by Django 5.0 on 2023-12-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jersey_store', '0011_order_created_order_paid_order_paystack_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paystack_ref',
        ),
    ]
