# Generated by Django 4.2.2 on 2023-12-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jersey_store', '0014_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('Jersey', 'Jersey'), ('Boot', 'Boots'), ('Accessories', 'Accessories')], max_length=50, null=True),
        ),
    ]
